version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Weiser32
      - DB_NAME=calevent_db
    entrypoint: /bin/bash -c "/src/wait-for.sh && http-server dist"

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Weiser32
      MYSQL_DATABASE: calevent_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pWeiser32",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  mysql-data:
